#!/bin/bash
set -e

# Utilisation des variables chargées par Docker
psql -v ON_ERROR_STOP=1 --username "$DB_USER" --dbname "$DB_NAME" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE USER $LLM_USER WITH PASSWORD '$LLM_PWD';
    GRANT CONNECT ON DATABASE $DB_NAME TO $LLM_USER;
    GRANT USAGE ON SCHEMA public TO $LLM_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO $LLM_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $LLM_USER;
EOSQL
